### ISSUE TITLE
iOS11 not working

### ISSUE THREAD

**Issue by al404** [AubreyHewes/cordova-background-audio#13]
Hi

On my phonegap app is not working anymore with iOS11 update

**Comment by fdambrosio** [comment]
Hi, there's a solution?

**Comment by AubreyHewes** [comment]
@al404 @fdambrosio Sorry, I have a limited investment in this project (see the project readme), I am open to contributors.
I will probably run in to this problem when one of original customers get a new phone ;-). My apologies.

**Comment by AubreyHewes** [comment]
maybe @EddyVerbruggen https://github.com/EddyVerbruggen/cordova-plugin-backgroundaudio/
