### ISSUE TITLE
its work in appstore

### ISSUE THREAD

**Issue by qamoooos** [AubreyHewes/cordova-background-audio#3]
Hello thank u for ur plugin 

just I want to know if its allowed to use this plugin in appstore and what I should do and what should not do to accept this plugin in appstore , 

Last question 

This plugin keep application running in background such as track location , send some data for server while application in background? Or just playing audio in back ground ?

**Comment by AubreyHewes** [comment]
This is purely for playing audio in background; no location dependencies etc. Unfocused app keeps playing audio. Yes is accepted by store.
