### ISSUE TITLE
If i would play a playlist in background?

### ISSUE THREAD

**Issue by fedepasi** [AubreyHewes/cordova-background-audio#6]
If i play only onw audio i background the plugin work fine, but if i try to play 2 audio in sequence, the second don't start, why?
I have to add anything else?

Thank you

**Comment by elgerlambert** [comment]
Came to say we're experiencing a similar issue, it used to work fine on iOS 9.2.x, but something has changed in iOS 9.3 and this had stopped working unfortunately - player stops after a song ends when the screen is locked. If I unlock (and our app re-appears) the music immediately starts playing again without any interaction required.

**Comment by neoassyrian** [comment]
Is there a solution for this? I'm having the same issue where it is not starting.

Is this something that can be added to the plugin
http://sapandiwakar.in/switch-to-a-new-song-in-background-for-ios/

**Comment by AubreyHewes** [comment]
Sorry, I am not actively developing this project (it still works for the original customer).  See the readme. 
@neoassyrian I am open to pr/contributors. See the readme.
