### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Heshyo** [AubreyHewes/cordova-background-audio#7]
I'm using the following configuration on Phonegap Build, but still whenever I click the home button, the stream I'm playing fades out. Any idea why?

```
<plugin name="cordova-plugin-media" source="npm" />
<plugin spec="https://github.com/AubreyHewes/cordova-background-audio.git" />
```

**Comment by Heshyo** [comment]
Is anyone having the same issue? Or am I using the plugin wrong?
I'm testing on iOS 9.3.2.

**Comment by AubreyHewes** [comment]
possibly #9

**Comment by Heshyo** [comment]
Actually I tried several plugins and none were working (through Phonegap Build). I'm currently using https://github.com/EddyVerbruggen/cordova-plugin-backgroundaudio but I also added the following to my config.xml 

```
<config-file platform="ios" parent="UIBackgroundModes" overwrite="true">
    <array>
        <string>audio</string>
    </array>
</config-file>
```

Maybe that setting, which is supposed to be added by the plugin, was somehow not added or overwritten by something else.
