### ISSUE TITLE
Any version of the plugin no longer works with Phonegap build version CLI.5.2.0 or greater.   .

### ISSUE THREAD

**Issue by SharonForster** [AubreyHewes/cordova-background-audio#9]
Use to work great but now build rejects this plugin.   I have tried various formats of the thing in config.xml such as 
<gap:plugin name="nl.kingsquare.background-audio" version="1.0.1" />
<plugin name="nl.kingsquare.background-audio" source="npm" />.

Nothing seems to build.  I desperately need this plug-in to function in my app.  Any help would be appreciated.

**Comment by miguelbn** [comment]
I second this. Until last month it was working fine. Now I get the error:
Error - The following plugin, plugin version or a dependancy of this plugin is not on npm: nl.kingsquare.background-audio

In my config.xml the plugin is added like this:
<plugin name="nl.kingsquare.background-audio" source="npm" />

I also tried:
<plugin name="nl.kingsquare.background-audio" source="npm" spec="1.0.1" />
<plugin name="nl.kingsquare.background-audio" source="npm" version="1.0.1" />
<gap:plugin name="nl.kingsquare.background-audio" version="1.0.1" />

**Comment by miguelbn** [comment]
OK, I figured it out with the help of Phonegap Build Forum.
Actually, the correct config.xml entry should be:
`<plugin name="nl.kingsquare.cordova.background-audio" source="npm" />`

The readme.md says it should be:
`<gap:plugin name="nl.kingsquare.background-audio" />`

This doesn't work anymore. The source must be NPM and the plugin ID is different there.

I proposed a change to readme.md to correct this.

**Comment by AubreyHewes** [comment]
I will look into this. Currently the app this was made for does not experience this problem. Though I have understood that we no longer use pgb for that app :-S

**Comment by AubreyHewes** [comment]
@miguelbn PR? "I proposed a change to readme.md to correct this."

**Comment by AubreyHewes** [comment]
maybe @EddyVerbruggen https://github.com/EddyVerbruggen/cordova-plugin-backgroundaudio/
